/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "tertiary-fixed-dim": "#f2bc89",
        "on-secondary-fixed-variant": "#374a50",
        "inverse-primary": "#9bcee0",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f4f5",
        "surface-container-highest": "#e2e2e4",
        "outline-variant": "#c0c8cb",
        "inverse-on-surface": "#f0f1f2",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d2e6ee",
        "on-surface": "#191c1d",
        "on-primary-fixed": "#001f27",
        "on-secondary-fixed": "#0b1e24",
        "secondary-fixed-dim": "#b6cad2",
        "primary-fixed": "#b7ebfd",
        "on-error": "#ffffff",
        "surface-container": "#edeeef",
        "outline": "#70787c",
        "on-background": "#191c1d",
        "primary-fixed-dim": "#9bcee0",
        "on-tertiary-fixed-variant": "#643e16",
        "tertiary": "#3c1f00",
        "surface-bright": "#f9f9fa",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2e3132",
        "on-primary-container": "#7baebf",
        "secondary-container": "#d2e6ee",
        "secondary": "#4f6168",
        "on-tertiary-container": "#cf9c6c",
        "on-tertiary-fixed": "#2d1600",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#144d5c",
        "primary-container": "#004251",
        "on-primary": "#ffffff",
        "surface": "#f9f9fa",
        "background": "#f9f9fa",
        "on-secondary-container": "#55676e",
        "primary": "#002b35",
        "surface-tint": "#316575",
        "tertiary-container": "#57340c",
        "surface-variant": "#e2e2e4",
        "surface-dim": "#d9dadb",
        "tertiary-fixed": "#ffdcbe",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#40484b",
        // Custom additions
        "success": "#1b6e2d",
        "success-container": "#a4f5ab",
        "on-success-container": "#004f16",
        "warning": "#7d5800",
        "warning-container": "#ffdea6",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "display": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
